name: Test Push
on:
  push:
  workflow_dispatch:
jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: detect kernel changed
        run: |
          mkdir tmp
          cd tmp
          git config --global init.defaultBranch bot
          git config --global user.name 'Bot'
          git config --global user.email 'bot@github.5ec1cff.io'
          git init .
          git remote add origin https://github.com/${{ github.repository }}
          AFTER_COMMIT="${{ github.event.after }}"
          git fetch origin $AFTET_COMMIT --depth=1
          BEFORE_COMMIT="${{ github.event.before }}"
          git fetch origin $BEFORE_COMMIT --depth=1
          set +e
          git diff --quiet $BEFORE_COMMIT $AFTER_COMMIT -- kernel
          echo "kernel changed: $?"
          set -e
