name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  aa:
    runs-on: ubuntu-latest

    steps:
      - name: Echo event
        run: |
          echo '--------------commits---------------------'
          echo '${{ toJson(github.event.commits) }}'
          echo '----------------event---------------------'
          echo '${{ toJson(github.event) }}'
